# Server configuration
server.port: 8082

# Database configuration
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

# Vaadin configuration
vaadin.allowed-packages: com.vaadin,org.vaadin,com.vaadin.starter.business
vaadin.pnpm.enable: true
# Logging
logging.level.org.atmosphere: warn
logging.level.com.vaadin.starter.business: info

# Clients basePath
api-configuration:
  customers:
    base-path: http://localhost:8086
  accounts:
    base-path: http://core-banking-accounts-dev.core.svc.cluster.local:8080/
  cards:
    base-path: http://localhost:8084
  contracts:
    base-path: http://common-platform-contract-mgmt-dev.common.svc.cluster.local:8080/
  products:
    base-path: http://common-platform-product-mgmt-dev.common.svc.cluster.local:8080/
  distributors:
    base-path: http://localhost:8084/
  catalogs:
    base-path: http://localhost:8084/

vaadin:
  async-supported: true